### ISSUE TITLE
Can't switch MiP into app mode on newer MiP robots

### ISSUE THREAD

**Issue by adamgreen** [adamgreen/MiP_ProMini-Pack#13]
I just tried installing one of my MiP ProMini boards on a recently purchased MiP and it fails to connect to the MiP as @Tiogaplanet describes in https://github.com/WowWeeLabs/MiP-BLE-Protocol/issues/20. 

I have entered this issue to track my investigation into this issue from my end to see if it is caused by a hardware/software issue that I introduced or can work around.

My hardware version shows up as the following in the official iOS application:
```d060217 v1 bV0.6```

**Comment by adamgreen** [comment]
Like @Tiogaplanet, I saw that not much happened at all until the first byte was changed from 0xFF to 0x00.

I attached a logic analyzer to watch the data sent back and forth between the MiP and ProMini-Pack. The logic analyzer output showed something very interesting after the 0x00 was sent instead of 0xFF. Once this change was made I saw that the MiP was responding with the following text, ```"FF01"```, at a rate of 9600 bps instead of the expected 115200.

I changed the bit rate in my Arduino library from 115200 bps to 9600 bps and then the sample started working as expected. I will spend time experimenting with solutions that might be able to auto detect this newer hardware and change the baud rate as necessary.

**Comment by adamgreen** [comment]
@Tiogaplanet I suspect if you switch the baud rate at [this line](https://github.com/adamgreen/MiP_ProMini-Pack/blob/master/Arduino/MiP_ProMini_Pack_Library/src/mip.cpp#L54) to 9600, you can probably install your original Sparkfun board in the newer MiP that you have and it will work. Just note that the communications back to the PC will also be at 9600 baud so you will have to change the rate in the Arduino serial monitor as well.

This isn't a long term fix for me but I just think it interesting that the original Sparkfun board might work  on these newer bots where you hit the problem.

**Comment by Tiogaplanet** [comment]
@adamgreen, good thing I still have it!  Thanks for the reminder.

Just received two more MiPs as dedicated platforms for your boards.  Will test your solution with either the original @SparkFun [board](https://github.com/sparkfun/MiP_ProMini-Pack) or an ESP8266 on the MiP I was using when I discovered the problem.

**Comment by adamgreen** [comment]
Fixed with commit 90f350b511f444b093d5459f8597a727d6d981a8

The library now attempts to connect with the MiP at 115200 baud and if that fails, it falls back to 9600 baud instead. It always communicates with the PC at 115200 baud.
