### ISSUE TITLE
Add Set Game Mode APIs

### ISSUE THREAD

**Issue by adamgreen** [adamgreen/MiP_ProMini-Pack#4]
[Original feedback](https://github.com/adamgreen/MiP_ProMini-Pack/issues/1#issuecomment-388337350) from @Tiogaplanet:
> I don't see any setGame functions but I may have overlooked them.

Rather than adding a public setGame() function, we could follow the enableRadarMode(), disableRadarMode(), enableGestureMode(), etc APIs to add functions like:
* enableCageMode()
* enableDanceMode()
* enableStackPlayMode()
* etc.

@Tiogaplanet, would you like to try adding this support? If not, I can try my hand at it as well.

**Comment by Tiogaplanet** [comment]
OK, I've started.  May take me a few nights but I'll have it done.

**Comment by adamgreen** [comment]
Excellent!

**Comment by Tiogaplanet** [comment]
OK, I made some progress last night. The setters appear to be working but the read function needs debugging. You can see my latest in this [commit](https://github.com/Tiogaplanet/MiP_ProMini-Pack/commit/7fc41f6923bbeff6da944f54669237e9327d1fd1).

**Comment by adamgreen** [comment]
Looks good. I just added a few comments to the commit.

**Comment by adamgreen** [comment]
@Tiogaplanet fixed with PR #6
